#!/bin/bash

#SBATCH --time=1:00:00   # walltime
#SBATCH -p defq
#SBATCH --array=0-105           # job array of size 105
SAVEIFS=$IFS   # Save current IFS
IFS=$'\n'      # Change IFS to new line
list=('NJ-BioR-118_TAATACAG-ATATTCAC_HG7LYDSXY'
'NJ-BioR-220_CGGCGTGA-GCGCCTGT_HG7LYDSXY'
'NJ-BioR-221_CATAGAGT-TGCCACCA_HG7LYDSXY'
'NJ-BioR-222_ATGTAAGT-ACTCTATG_HG7LYDSXY'
'NJ-BioR-223_GCACGGAC-GTCTCGCA_HG7LYDSXY'
'NJ-BioR-224_ACAGGCGC-CTCTGCCT_HG7LYDSXY'
'NJ-BioR-225_GGTACCTT-AAGACGTC_HG7LYDSXY'
'NJ-BioR-226_GTGAATAT-TCTCATTC_HG7LYDSXY'
'NJ-BioR-227_AACGTTCC-GGAGTACT_HG7LYDSXY'
'NJ-BioR-228_GCAGAATT-ACCGGCCA_HG7LYDSXY'
'NJ-BioR-229_ATGAGGCC-GTTAATTG_HG7LYDSXY'
'NJ-BioR-230_AACTGTAG-ACGCCGCA_HG7LYDSXY'
'NJ-BioR-231_GGTCACGA-GTATTATG_HG7LYDSXY'
'NJ-BioR-232_GTCGGAGC-GGTTATAA_HG7LYDSXY'
'NJ-BioR-233_CTTGGTAT-CCAAGTCC_HG7LYDSXY'
'NJ-BioR-234_TCCAACGC-TTGGACTT_HG7LYDSXY'
'NJ-BioR-236_CTGCTTCC-GATAGATC_HG7LYDSXY'
'NJ-BioR-237_CCGTGAAG-CAGTGGAT_HG7LYDSXY'
'NJ-BioR-238_TTACAGGA-TGACAAGC_HG7LYDSXY'
'NJ-BioR-239_GGCATTCT-CTAGCTTG_HG7LYDSXY'
'NJ-BioR-240_TCATCCTT-AGCGAGCT_HG7LYDSXY'
'NJ-BioR-242_AGGTTATA-CAGTTCCG_HG7LYDSXY'
'NJ-BioR-243_AATGCCTC-TCGATCCA_HG7LYDSXY'
'NJ-BioR-244_TACCGAGG-CCTGAACT_HG7LYDSXY'
'NJ-BioR-245_GAACCGCG-TGACCTTA_HG7LYDSXY'
'NJ-BioR-246_CTCACCAA-CTAGGCAA_HG7LYDSXY'
'NJ-BioR-247_CGTTAGAA-TTCAGGTC_HG7LYDSXY'
'NJ-BioR-248_AGCCTCAT-AGTAGAGA_HG7LYDSXY'
'NJ-BioR-249_GATTCTGC-GACGAGAG_HG7LYDSXY'
'NJ-BioR-250_TCTGTTGG-TCGAATGG_HG7LYDSXY'
'NJ-BioR-251_TATCGCAC-CTTAGTGT_HG7LYDSXY'
'NJ-BioR-252_TCGTAGTG-AGACTTGG_HG7LYDSXY'
'NJ-BioR-254_CTACGACA-GAGTCCAA_HG7LYDSXY'
'NJ-BioR-255_TAAGTGGT-CTTAAGCC_HG7LYDSXY'
'NJ-BioR-256_CGGACAAC-TCCGGATT_HG7LYDSXY'
'NJ-BioR-257_CGCTATGT-TCCGACAC_HG7LYDSXY'
'NJ-BioR-258_GTATGTTC-AACAGGAA_HG7LYDSXY'
'NJ-BioR-259_ATATGGAT-CTGTATTA_HG7LYDSXY'
'NJ-BioR-261_GCGCAAGC-TCACGCCG_HG7LYDSXY'
'NJ-BioR-262_AAGATACT-ACTTACAT_HG7LYDSXY'
'NJ-BioR-263_ACGCACCT-GGTGAAGG_HG7LYDSXY'
'NJ-BioR-264_GGAGCGTC-GTCCGTGC_HG7LYDSXY'
'NJ-BioR-265_ATGGCATG-AAGGTACC_HG7LYDSXY'
'NJ-BioR-266_GCAATGCA-GGAACGTT_HG7LYDSXY'
'NJ-BioR-267_GTTCCAAT-AATTCTGC_HG7LYDSXY'
'NJ-BioR-268_TACTCATA-CCTGTGGC_HG7LYDSXY'
'NJ-BioR-269_ACCTTGGC-GGCCTCAT_HG7LYDSXY'
'NJ-BioR-270_ATATCTCG-ATCTTAGT_HG7LYDSXY'
'NJ-BioR-271_GCGCTCTA-GCTCCGAC_HG7LYDSXY'
'NJ-BioR-272_AACAGGTT-ATACCAAG_HG7LYDSXY'
'NJ-BioR-273_GGTGAACC-GCGTTGGA_HG7LYDSXY'
'NJ-BioR-274_CGTCTGCG-TTCACAAT_HG7LYDSXY'
'NJ-BioR-275_CAACAATG-CTTCACGG_HG7LYDSXY'
'NJ-BioR-276_TCGATATC-ACACGAGT_HG7LYDSXY'
'NJ-BioR-277_TGGTGGCA-TCCTGTAA_HG7LYDSXY'
'NJ-BioR-278_CTAGCGCT-GTGTAGAC_HG7LYDSXY'
'NJ-BioR-279_CCGCGGTT-AGCGCTAG_HG7LYDSXY'
'NJ-BioR-280_GAATGAGA-GAGGCATT_HG7LYDSXY'
'NJ-BioR-282_TTATAACC-GATATCGA_HG7LYDSXY'
'NJ-BioR-283_GGACTTGG-CGCAGACG_HG7LYDSXY'
'NJ-BioR-284_ATCCACTG-AGGTGCGT_HG7LYDSXY'
'NJ-BioR-285_GCTTGTCA-GAACATAC_HG7LYDSXY'
'NJ-BioR-287_CAAGCTAG-ACATAGCG_HG7LYDSXY'
'NJ-BioR-288_TGGATCGA-GTGCGATA_HG7LYDSXY'
'NJ-BioR-289_TGCGGCGT-CCTCGGTA_HG7LYDSXY'
'NJ-BioR-290_CATAATAC-TTCTAACG_HG7LYDSXY'
'NJ-BioR-291_GATCTATC-ATGAGGCT_HG7LYDSXY'
'NJ-BioR-292_AGCTCGCT-GCAGAATC_HG7LYDSXY'
'NJ-BioR-293_CGGAACTG-CACTACGA_HG7LYDSXY'
'NJ-BioR-294_TAAGGTCA-TGTCGTAG_HG7LYDSXY'
'NJ-BioR-295_AGTTCAGG-CCAACAGA_HG7LYDSXY'
'NJ-BioR-296_TTGCCTAG-ACCACTTA_HG7LYDSXY'
'NJ-BioR-297_CCATTCGA-GTTGTCCG_HG7LYDSXY'
'NJ-BioR-298_ACACTAAG-ATCCATAT_HG7LYDSXY'
'NJ-BioR-299_GACCTGAA-TTGGTGAG_HG7LYDSXY'
'NJ-BioR-29_TGCGAGAC-CATTGTTG_HG7LYDSXY '
'NJ-BioR-300_GTGTCGGA-GCTTGCGC_HG7LYDSXY'
'NJ-BioR-301_TTCCTGTT-AGTATCTT_HG7LYDSXY'
'NJ-BioR-302_CCTTCACC-GACGCTCC_HG7LYDSXY'
'NJ-BioR-303_GCCACAGG-CATGCCAT_HG7LYDSXY'
'NJ-BioR-304_ATTGTGAA-TGCATTGC_HG7LYDSXY'
'NJ-BioR-305_TCTCTACT-CGCGGTTC_HG7LYDSXY'
'NJ-BioR-306_ACTCGTGT-ATTGGAAC_HG7LYDSXY'
'NJ-BioR-307_GTCTACAC-GCCAAGGT_HG7LYDSXY'
'NJ-BioR-308_CAATTAAC-CGAGATAT_HG7LYDSXY'
'NJ-BioR-310_CTCTCGTC-TATAACCT_HG7LYDSXY'
'NJ-BioR-312_CCAAGTCT-AAGGATGA_HG7LYDSXY'
'NJ-BioR-313_TGGCCGGT-TAGAGCGC_HG7LYDSXY'
'NJ-BioR-314_AGTACTCC-AACCTGTT_HG7LYDSXY'
'NJ-BioR-315_CCGCGGTT-AGCGCTAG_HG7LYDSXY'
'NJ-BioR-316_TTATAACC-GATATCGA_HG7LYDSXY'
'NJ-BioR-317_GGACTTGG-CGCAGACG_HG7LYDSXY'
'NJ-BioR-318_AAGTCCAA-TATGAGTA_HG7LYDSXY'
'NJ-BioR-319_ATCCACTG-AGGTGCGT_HG7LYDSXY'
'NJ-BioR-320_GCTTGTCA-GAACATAC_HG7LYDSXY'
'NJ-BioR-321_CAAGCTAG-ACATAGCG_HG7LYDSXY'
'NJ-BioR-322_TGGATCGA-GTGCGATA_HG7LYDSXY'
'NJ-BioR-323_AGTTCAGG-CCAACAGA_HG7LYDSXY'
'NJ-BioR-325_GACCTGAA-TTGGTGAG_HG7LYDSXY'
'NJ-BioR-326_TCTCTACT-CGCGGTTC_HG7LYDSXY'
'NJ-BioR-327_CTCTCGTC-TATAACCT_HG7LYDSXY'
'NJ-BioR-328_GACGTCTT-GGTTCACC_HG7LYDSXY'
'NJ-BioR-330_CCAAGTCT-AAGGATGA_HG7LYDSXY'
'NJ-BioR-331_TTGGACTC-GGAAGCAG_HG7LYDSXY'
'NJ-BioR-332_GGCTTAAG-TCGTGACC_HG7LYDSXY'
'NJ-BioR-333_AATCCGGA-CTACAGTT_HG7LYDSXY')
filename=${list[${SLURM_ARRAY_TASK_ID}]}

mkdir sub_results_"$filename"
mkdir sub_results_"$filename"/pathomap-Pathoscope
mkdir sub_results_"$filename"/pathomap-Pathoscope/bacterialRefBowtie2
mkdir sub_results_"$filename"/pathomap-Pathoscope/humanRef
mkdir sub_results_"$filename"/pathomap-Pathoscope/viralRef
seqtk sample -s100 AllFastqFiles/"$filename"_R1_cat.fastq 100000 > sub_"$filename"_R1.fq
seqtk sample -s100 AllFastqFiles/"$filename"_R2_cat.fastq 100000 > sub_"$filename"_R2.fq
cutadapt -a AGATCGGAAGAG -A AGATCGGAAGAG -o sub_tr_"$filename"_R1.fastq -p sub_tr_"$filename"_R2.fastq sub_"$filename"_R1.fastq sub_"$filename"_R2.fastq
pathoscope MAP -1 sub_tr_"$filename"_R1.fastq -2 sub_tr_"$filename"_R1.fastq \
-numThreads 40 \
-indexDir . \
-targetIndexPrefixes Pathoscope/bacterialRefBowtie2/allBacGenomes \
-filterIndexPrefixes Pathoscope/humanRef/GCF_000001405.39_GRCh38.p13_genomic.fna_bt2,Pathoscope/viralRef/allViralRefSeqGenomes.fna_bt2 \
-outDir sub_results_"$filename" \
-outAlign "$filename".sam
pathoscope ID -alignFile sub_results_"$filename"/"$filename".sam -fileType sam -outDir sub_results_"$filename" -expTag "$filename"
#rm results_"$filename"/pathomap-Pathoscope/bacterialRefBowtie2/*.sam
#rm results_"$filename"/pathomap-appendAlign.sam
$IFS=$SAVEIFS
